### ISSUE TITLE
Problem encountered when installing v 0.0.2 via pip

### ISSUE THREAD

**Issue by gsvr** [c-goosen/za_identity_number#2]
Hi @c-goosen! Thanks for publishing this package :)

I'm hitting an error when trying to install new release 0.0.2 via pip (0.0.1 is still working):

`poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package za-identity-number`

I had a quick look and I think underscores should be used here: https://github.com/c-goosen/za_identity_number/blob/9cfb06160c8f649073d889118790b39c43e2120e/setup.py#L38

**Comment by c-goosen** [comment]
@gsvr Please try version 0.0.3

Looks like its working.

**Comment by c-goosen** [comment]
Just fyi don't think that was the only problem, so did some cleaning up of pip & poetry

**Comment by gsvr** [comment]
@c-goosen Yup, it's working :)

I had to change the import name but that's not an issue. Thanks!

**Comment by c-goosen** [comment]
@gsvr Perfect. Made some slightly breaking changes just for ease of use.

Welcome to open issues as feature requests if there is anything I didn't think of
