### ISSUE TITLE
Value Error for ID Number starting with 000000

### ISSUE THREAD

**Issue by arieroos** [c-goosen/za_identity_number#4]
`SouthAfricanIdentityValidate("0000000000000").validate()` raises a ValueError. I would expect that is just returns False.

I will submit a PR soon

**Comment by c-goosen** [comment]
Thanks for catching that. I can also fix it. Busy adding a test for it

**Comment by arieroos** [comment]
Thank you @c-goosen. I also have test cases in my PR
