### ISSUE TITLE
Loguru configuration in ID constructor

### ISSUE THREAD

**Issue by philip-sterne** [c-goosen/za_identity_number#7]
The current code calls loguru configuration in the construction of every ZA ID number.

According to [Loguru documentation](https://loguru.readthedocs.io/en/stable/overview.html#suitable-for-scripts-and-libraries), best practice is to only do configuration in calling scripts and disable library logging by default. (It's easy enough to re-enable in a script if desired.)

**Comment by c-goosen** [comment]
Addressed in latest version 0.0.7
